### ISSUE TITLE
Checkout components no longer work in winter 24

### ISSUE THREAD

**Issue by dennis-graves** [commerce-codeitforward/Components-For-Salesforce-Commerce-Cloud#2]
With the winter 24 release and the new checkout components (Layout - One Page/Layout - Accordian) the checkout validation no longer occurs the same as in previous versions. 

Fix: 

import { CheckoutComponentBase } from 'commerce/checkoutApi';
const CheckoutStage = {
    CHECK_VALIDITY_UPDATE: 'CHECK_VALIDITY_UPDATE',
    REPORT_VALIDITY_SAVE: 'REPORT_VALIDITY_SAVE',
    BEFORE_PAYMENT: 'BEFORE_PAYMENT',
    PAYMENT: 'PAYMENT',
    BEFORE_PLACE_ORDER: 'BEFORE_PLACE_ORDER',
    PLACE_ORDER: 'PLACE_ORDER'
};
export default class CheckoutExampleTerms extends CheckoutComponentBase {

 /**
     * update form when our container asks us to
     */
    stageAction(checkoutStage /*CheckoutStage*/) {
        switch (checkoutStage) {
            case CheckoutStage.CHECK_VALIDITY_UPDATE:
                return Promise.resolve(this.checkValidity());
            case CheckoutStage.REPORT_VALIDITY_SAVE:
                return Promise.resolve(this.reportValidity());
            case CheckoutStage.PAYMENT:
                return this.completePayment();
            default:
                return Promise.resolve(true);
        }
    }

//reportValidity() method just call the checkValidity()
//checkValidity() method checks if the component is valid and shows error otherwise
// completePayment() method used to perform actions when order is being placed, ie payment or other updates
}

**Comment by spsmyth0426** [comment]
Thanks for the comment @dennis-graves! It took me a bit to get back to this but this is now resolved in the component.
